/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import EMovieStore.MovieStoreItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Logger;

/**
 *
 * @author mark4689
 */
public class AdminInventory extends javax.swing.JPanel {
    private ArrayList<MovieStoreItem> invList = new ArrayList();
    private ResultSet listData;
    /**
     * Creates new form AdminInventory
     */
    public AdminInventory() throws SQLException {
        initComponents();
       
        listData = EMovieStoreFrame.getDBA().runQuery("SELECT * FROM INVENTORY");
        while(listData.next()){
            MovieStoreItem msi = new MovieStoreItem(listData.getString("class"),listData.getInt("copiesavailable"),
                    listData.getInt("copiestotal"),listData.getInt("rentalperiod"), listData.getDouble("rentalRate"),
                    listData.getString("status"), listData.getString("titlename"));
            invList.add(msi);
                    //MovieStoreItem(String classification, int numAvailable, int numCopies, 
                    //int rentalPeriod,double rentalRate, String status, String title)
        }
        
        jList1.setListData(invList.toArray());
        
        jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int numSelected = jList1.getSelectedIndices().length;
                String SQL_Statement;
                if(jComboBox1.getSelectedItem().equals("Available")||jComboBox1.getSelectedItem().equals("NotAvailable")){
                for(int i = 0; i < numSelected; i++){
                    SQL_Statement = "UPDATE INVENTORY SET STATUS = ? WHERE TITLENAME =";
                    try {
                        EMovieStoreFrame.getDBA().runQuery(SQL_Statement);
                    } catch (SQLException ex) {
                        System.out.println(ex);
                    }
                }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane1.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add", "Delete", "NotAvailable", "Available", " " }));

        jButton1.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
